version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - mongohost  # указываем, что web-сервис должен подождать запуска MongoDB

  mongohost:
    image: "mongo:latest"  # используем официальный образ MongoDB
    ports:
      - "27017:27017"
