version: "3.8"
services:
  web:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  mongohost:
    image: "mongo:latest"
    ports:
      - "27017:27017"
